title: Jiyoon's cloud voyage
logo: /assets/img/logo.jpg
email: dwsrh03@gmail.com
description: The course of growth as a Cloud Engineer
favicon: true
color-scheme: auto
futrue: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://zyoonshin.github.io/
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: 

navigation:
  - name: Naver Cloud Camp
    sublist:
      - name: Curriculum
  - name : Concept
    link : [curriculum](index.md#curriculum)
    sublist:
      - name: Markdown
        link: [markdown](index.md#markdown)
      - name: Hypervisor
        link: [hypervisor](hypervisor.md)
      - name: Remote
        link: [remote](index.md#hypervisor)
  - name: Another Page
    link: ./another-page.md