title: Jiyoon's cloud voyage
logo: /assets/img/logo.jpg
email: dwsrh03@gmail.com
description: The course of growth as a Cloud Engineer
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/zyoonshin/zyoonshin.github.io
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: 

navigation:
  - name: Naver Cloud Camp
    sublist:
      - name: Curriculum
  - name : Concept
    link : ./index.md
    sublist:
      - name: Markdown
        link: [markdown](markdown.md)
    
      - name: Hypervisor
        link: [hypervisor](hypervisor.md)
  - name: Another Page
    link: ./another-page.md